name: security_demo

services:
  postgres:
    image: postgres:17.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - network
    restart: unless-stopped

networks:
  network:
    name: security_intro_network
    driver: bridge

volumes:
  postgres:
    name: security_intro_postgres